spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: 088990656512345678Vv#
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: never

mail:
  host: ${MAIL_HOST:localhost}
  port: ${MAIL_PORT:1025}
  username: ${MAIL_USERNAME:admin@example.com}
  password: ${MAIL_PASS:}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8081
  endpoint:
    info:
      enabled: true

mobilele:
  admin:
    defaultpass: ${DEFAULT_PASS:test}
